[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/doxav/astromodel_proving/blob/main/analysis/09_reviewer_response_synthesis.ipynb)

# Step 09 - Reviewer-response synthesis

This notebook integrates Steps 00-08 into reviewer-facing traceability, claim-maturity, and manuscript asset tables. It creates no new biological evidence and does not upgrade claims beyond what upstream outputs support.

In [1]:
from pathlib import Path
import os
import pandas as pd

PROJECT_ROOT = Path(os.environ.get("ASTROMODEL_PROJECT_ROOT", ".")).resolve()
PROJECT_ROOT

PosixPath('/home/xav/code/astromodel_proving')

In [2]:
from src.step09_reviewer_synthesis import Step09Config, run_step09_reviewer_synthesis

config = Step09Config(write_outputs=True)
result = run_step09_reviewer_synthesis(PROJECT_ROOT, config)
result["analysis_summary"]

{'step_name': 'Step 09 - reviewer-response synthesis',
 'config': {'write_outputs': True},
 'n_reviewer_rows': 7,
 'n_claim_rows': 6,
 'n_manifest_rows': 12,
 'missing_manifest_artifacts': [],
 'final_biological_degeneracy_claim_allowed': False,
 'headline_claim_scope': 'Final degeneracy wording is allowed only if all upstream evidence layers are supported.',
 'elapsed_seconds': 0.023015669001324568}

## R1-R7 traceability

In [3]:
traceability = result["reviewer_traceability_table"]
traceability

,reviewer_id,critique,primary_outputs,evidence_status,claim_boundary,final_biological_degeneracy_claim_allowed
0,R1,degeneracy versus non-identifiability/sloppiness,outputs/identifiability; outputs/mechanisms; o...,supported,Degeneracy wording remains disabled unless Ste...,False
1,R2,"experimental variability, noise, and data cons...",outputs/provenance; outputs/features,supported,Cell/file is the independent unit; no paired a...,False
2,R3,model assumptions and proxy validity,outputs/assumption_sensitivity,partial,Explicit ECS/proxy variants remain required wh...,False
3,R4,Vm-only fits and physiological parameter plaus...,outputs/identifiability; outputs/parameter_pla...,supported,Raw parameters are interpreted only when range...,False
4,R5,"pathways, mechanisms, and phenotypes",outputs/mechanisms; outputs/predictive_validation,supported,Phenotype tags are provisional until predictio...,False
5,R6,held-out prediction and perturbation robustness,outputs/predictive_validation,supported,Prediction-limited or fit-only clusters are no...,False
6,R7,"clarity, organization, units, and figure trace...",outputs/reviewer_synthesis/manuscript_asset_ma...,supported,Figures/tables must cite source step outputs a...,False

## Claim maturity

In [4]:
maturity = result["claim_maturity_table"]
maturity

,claim,maturity,basis,remaining_requirement,mean_biological_description_score
0,accepted cell-specific six-sweep ensembles exist,supported,Step 04 accepted ensemble and held-out-current...,increase accepted/reviewer-facing cell coverag...,0.657225
1,candidate mechanism regimes are biologically i...,candidate_regime_screen,"Step 05 hidden-current, windowed phenotype, cl...",requires Step 06 predictive/perturbation suppo...,0.657225
2,mechanism or phenotype labels are predictive u...,supported,Step 06 robustness labels and biological_descr...,"broaden support across region, condition, mech...",0.657225
3,model assumptions do not drive the conclusion,model_dependent_or_unresolved,"Step 07 gating, proxy, and compartment-split s...",explicit ECS variant or additional data if pro...,0.657225
4,accepted parameters are physiologically interp...,partial,"Step 08 range, identifiability, and constraine...",raw coordinates require both range and identif...,0.657225
5,final biological degeneracy wording is allowed,not_allowed_yet,Integrated Step 03-08 synthesis,"requires mechanism distinction, predictive sup...",0.657225

## Manuscript asset manifest

In [5]:
manifest = result["manuscript_asset_manifest"]
manifest

,step,artifact,purpose,exists,claim_scope
0,Step 00,outputs/provenance/atf_region_condition_invent...,ATF data provenance and region/condition audit,True,reviewer_facing_source_table
1,Step 02,outputs/features/condition_region_sweep_thresh...,Region-aware feature thresholds,True,reviewer_facing_source_table
2,Step 03,outputs/identifiability/effective_parameter_ma...,Effective-parameter and identifiability guardr...,True,reviewer_facing_source_table
3,Step 04,outputs/cell_fits/accepted_cell_ensembles.csv,Accepted six-sweep cell ensembles,True,reviewer_facing_source_table
4,Step 04,outputs/cell_fits/cell_fit_candidates.csv,Full candidate history for audit,True,reviewer_facing_source_table
5,Step 05,outputs/mechanisms/accepted_fit_mechanisms.csv,Hidden-current flux decomposition,True,reviewer_facing_source_table
6,Step 05,outputs/mechanisms/accepted_fit_mechanisms_win...,Windowed local/spatial mechanism characterization,True,reviewer_facing_source_table
7,Step 05,outputs/mechanisms/buffering_phenotype_tags.csv,Provisional phenotype tags,True,reviewer_facing_source_table
8,Step 06,outputs/predictive_validation/robustness_summa...,Prediction and perturbation robustness,True,reviewer_facing_source_table
9,Step 07,outputs/assumption_sensitivity/claim_scope_tab...,Assumption-sensitivity claim scope,True,reviewer_facing_source_table
10,Step 08,outputs/parameter_plausibility/interpretabilit...,Parameter interpretability guardrails,True,reviewer_facing_source_table
11,Step 09,outputs/reviewer_synthesis/reviewer_traceabili...,R1-R7 response map,True,reviewer_facing_source_table

## Objective synthesis conclusion

The final row below is generated from the actual upstream outputs. If final biological degeneracy wording is not allowed, the manuscript response should keep the claim at mechanism-screen or prediction-limited maturity and state the unresolved layer explicitly.

In [6]:
final_claim = maturity[maturity["claim"].eq("final biological degeneracy wording is allowed")]
display(final_claim)
assert set(traceability["reviewer_id"]) == {"R1", "R2", "R3", "R4", "R5", "R6", "R7"}
assert "final_biological_degeneracy_claim_allowed" in result["analysis_summary"]
print("Step 09 synthesis outputs written under", PROJECT_ROOT / "outputs" / "reviewer_synthesis")

,claim,maturity,basis,remaining_requirement,mean_biological_description_score
5,final biological degeneracy wording is allowed,not_allowed_yet,Integrated Step 03-08 synthesis,"requires mechanism distinction, predictive sup...",0.657225

Step 09 synthesis outputs written under /home/xav/code/astromodel_proving/outputs/reviewer_synthesis

## Post-execution scientific status

Executed status for reviewer response: Step 09 integrates R1-R7 into 7 traceability rows, 6 claim-maturity rows, and a complete 12-artifact manuscript manifest with no missing artifacts. The integrated maturity table marks accepted ensembles and predictive/perturbation evidence as supported, mechanism regimes as a candidate screen, assumptions as model-dependent/unresolved, parameter interpretability as partial, and final biological degeneracy wording as `not_allowed_yet`. This is the current objective model-proving state.