[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/doxav/astromodel_proving/blob/main/analysis/09_reviewer_response_synthesis.ipynb)

# Step 09 - Reviewer-response synthesis

This notebook integrates Steps 00-08 into reviewer-facing traceability, claim-maturity, manuscript asset tables, and selected reviewer-action gate audits.

## Scientific conclusion and usefulness

The current evidence supports a useful, constrained model-based mechanistic screen: the pipeline links ATF membrane kinetics, effective parameter structure, hidden K_o / flux summaries, legacy mechanism categories, and perturbation-direction tests into auditable tables. The model is useful for identifying falsifiable buffering hypotheses, parameter tradeoffs, K_o functional consequences, and reviewer-facing guardrails. It does not prove biological degeneracy: final wording remains blocked until mechanism distinction, predictive support, perturbation direction matching, assumption robustness, parameter plausibility, and external biological calibration are simultaneously satisfied.

## How to use each section

- **Selected-action gate audits**: checks derivative gates from existing outputs; use to see which claims are blocked, restricted, or supported without rerunning fitting.
- **Selected-action scientific value**: summarizes whether the derivative audits add scientific value or only bookkeeping.
- **R1-R7 traceability**: maps each reviewer concern to concrete outputs and conservative claim boundaries; use as the response-letter backbone.
- **Claim maturity**: states which manuscript claims are supported, restricted, unresolved, or not allowed.
- **Manuscript asset manifest**: inventory of source tables/figures and missing artifacts; use for methods/supplement organization.
- **Reviewer remark artifact links**: ordered links from each reviewer remark to the most useful upstream notebook cells and result files.
- **Legacy perturbation and mechanistic pathway gates**: first-pass mechanistic screen for MFA/MFA+BA-like perturbations; use as hypothesis generation, not proof.
- **Objective synthesis conclusion**: single-row scientific statement of current value and remaining requirements when biological degeneracy is not proven.
- **Restricted claim gates**: final wording guardrails; use to choose allowed and forbidden phrases for the manuscript and rebuttal.
- **Post-execution scientific status**: concise execution and interpretation status for this notebook.

In [1]:
from pathlib import Path
import os
import sys
import pandas as pd

pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 240)

PROJECT_ROOT = Path(os.environ.get("ASTROMODEL_PROJECT_ROOT", ".")).resolve()
if not (PROJECT_ROOT / "src").exists():
    current = Path.cwd().resolve()
    PROJECT_ROOT = next((p for p in [current, *current.parents] if (p / "src").exists()), PROJECT_ROOT)
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))
PROJECT_ROOT

PosixPath('/home/xav/code/astromodel_proving')

## Selected-action gate audits

In [2]:
from src.reviewer_gate_audits import ReviewerGateAuditConfig, run_reviewer_gate_audits

gate_config = ReviewerGateAuditConfig(write_outputs=True)
gate_result = run_reviewer_gate_audits(PROJECT_ROOT, gate_config)
pd.DataFrame([
    {"artifact": key, "n_rows": len(value), "n_columns": len(value.columns)}
    for key, value in gate_result.items()
]).sort_values("artifact").reset_index(drop=True)

                                         artifact  n_rows  n_columns
0                  K_o_homeostasis_endpoint_audit      18         13
1              all_current_assumption_sensitivity      90          7
2                           assumption_gate_audit       3          8
3             cell_specific_identifiability_audit     261         11
4                        claim_to_artifact_ledger       6          6
5                       constrained_failure_modes      29         13
6                          degeneracy_level_table      29         11
7                   full_accepted_parameter_audit    3177         27
8               integrated_degeneracy_gate_matrix      29         25
9           intercluster_interpolation_acceptance     270         18
10  notebook_update_screen_after_selected_actions      10          6
11           parameter_interpretation_class_audit     261         34
12                parameter_ranges_citation_audit       9         14
13                      parameter_semantics_audit       9         11
14                   phenotype_robustness_summary      18         13
15                phenotype_threshold_sensitivity     353         12
16               prediction_limited_failure_modes       0          0
17              proxy_exclusion_claim_sensitivity      10         11
18                       restricted_all_gate_join      29         15
19                   restricted_validation_claims      10          8
20                selected_action_results_summary      23          5
21    selected_action_scientific_value_assessment      22          5
22            selected_action_strategy_comparison       3          8
23                           stratum_support_gate       6         14

## Selected-action scientific value

In [3]:
selected_summary = pd.read_csv(PROJECT_ROOT / "outputs" / "reviewer_synthesis" / "selected_action_results_summary.csv")
scientific_value = pd.read_csv(PROJECT_ROOT / "outputs" / "reviewer_synthesis" / "selected_action_scientific_value_assessment.csv")
display(selected_summary)
display(scientific_value)

                                     artifact_key  n_rows  n_columns  non_empty  can_upgrade_claim_directly
0             selected_action_strategy_comparison       3          8       True                       False
1                    phenotype_robustness_summary      18         13       True                       False
2                            stratum_support_gate       6         14       True                       False
3                prediction_limited_failure_modes       0          0      False                       False
4                           assumption_gate_audit       3          8       True                       False
5               proxy_exclusion_claim_sensitivity      10         11       True                       False
6                       parameter_semantics_audit       9         11       True                       False
7                   full_accepted_parameter_audit    3177         27       True                       False
8            parameter_interpretation_class_audit     261         34       True                       False
9                       constrained_failure_modes      29         13       True                       False
10                 K_o_homeostasis_endpoint_audit      18         13       True                       False
11          intercluster_interpolation_acceptance     270         18       True                       False
12                phenotype_threshold_sensitivity     353         12       True                       False
13             all_current_assumption_sensitivity      90          7       True                       False
14            cell_specific_identifiability_audit     261         11       True                       False
15                parameter_ranges_citation_audit       9         14       True                       False
16  notebook_update_screen_after_selected_actions      10          6       True                       False
17              integrated_degeneracy_gate_matrix      29         25       True                       False
18                         degeneracy_level_table      29         11       True                       False
19                   restricted_validation_claims      10          8       True                       False
20                       restricted_all_gate_join      29         15       True                       False
21                       claim_to_artifact_ledger       6          6       True                       False
22    selected_action_scientific_value_assessment      22          5       True                       False

                                     artifact_key  n_rows  n_columns     scientific_value_status                                                          rationale
0             selected_action_strategy_comparison       3          8                      retain                               artifact has rows and explicit gates
1                    phenotype_robustness_summary      18         13                      retain                               artifact has rows and explicit gates
2                            stratum_support_gate       6         14                      retain                               artifact has rows and explicit gates
3                prediction_limited_failure_modes       0          0        remove_or_regenerate             artifact is empty and cannot support reviewer response
4                           assumption_gate_audit       3          8  retain_as_blocker_evidence  assumption gate failures are scientifically important limitations
5               proxy_exclusion_claim_sensitivity      10         11                      retain                               artifact has rows and explicit gates
6                       parameter_semantics_audit       9         11                      retain                               artifact has rows and explicit gates
7                   full_accepted_parameter_audit    3177         27                      retain                               artifact has rows and explicit gates
8            parameter_interpretation_class_audit     261         34                      retain                               artifact has rows and explicit gates
9                       constrained_failure_modes      29         13                      retain                               artifact has rows and explicit gates
10                 K_o_homeostasis_endpoint_audit      18         13                      retain                               artifact has rows and explicit gates
11          intercluster_interpolation_acceptance     270         18                      retain                               artifact has rows and explicit gates
12                phenotype_threshold_sensitivity     353         12                      retain                               artifact has rows and explicit gates
13             all_current_assumption_sensitivity      90          7                      retain                               artifact has rows and explicit gates
14            cell_specific_identifiability_audit     261         11                      retain                               artifact has rows and explicit gates
15                parameter_ranges_citation_audit       9         14                      retain                               artifact has rows and explicit gates
16  notebook_update_screen_after_selected_actions      10          6                      retain                               artifact has rows and explicit gates
17              integrated_degeneracy_gate_matrix      29         25                      retain                               artifact has rows and explicit gates
18                         degeneracy_level_table      29         11                      retain                               artifact has rows and explicit gates
19                   restricted_validation_claims      10          8                      retain                               artifact has rows and explicit gates
20                       restricted_all_gate_join      29         15  retain_as_blocker_evidence   all-gate join objectively shows final degeneracy remains blocked
21                       claim_to_artifact_ledger       6          6                      retain                               artifact has rows and explicit gates

In [4]:
from src.step09_reviewer_synthesis import Step09Config, run_step09_reviewer_synthesis

config = Step09Config(write_outputs=True)
result = run_step09_reviewer_synthesis(PROJECT_ROOT, config)
result["analysis_summary"]

{'step_name': 'Step 09 - reviewer-response synthesis',
 'config': {'write_outputs': True},
 'n_reviewer_rows': 7,
 'n_claim_rows': 6,
 'n_manifest_rows': 46,
 'n_reviewer_link_rows': 16,
 'n_pathway_gate_rows': 32,
 'missing_manifest_artifacts': [],
 'final_biological_degeneracy_claim_allowed': False,
 'headline_claim_scope': 'Final degeneracy wording is allowed only if all upstream evidence layers are supported.',
 'elapsed_seconds': 0.2294437939999625}

## R1-R7 traceability

In [5]:
traceability = result["reviewer_traceability_table"].drop(columns=["final_biological_degeneracy_claim_allowed"],errors="ignore",)
traceability

,reviewer_id,critique,primary_outputs,evidence_status,claim_boundary
0,R1,degeneracy versus non-identifiability/sloppiness,outputs/identifiability; outputs/mechanisms; outputs/reviewer_synthesis,supported,Degeneracy wording remains disabled unless Step 06 and Step 09 synthesis support it.
1,R2,"experimental variability, noise, and data constraints",outputs/provenance; outputs/features,supported,Cell/file is the independent unit; no paired animal-level claims are made.
2,R3,model assumptions and proxy validity,outputs/assumption_sensitivity,partial,Explicit ECS/proxy variants remain required when proxy rows are limited.
3,R4,Vm-only fits and physiological parameter plausibility,outputs/identifiability; outputs/parameter_plausibility,supported,Raw parameters are interpreted only when range and identifiability guardrails pass.
4,R5,"pathways, mechanisms, and phenotypes",outputs/mechanisms; outputs/legacy_mechanisms; outputs/predictive_validation; outputs/legacy_perturbation,supported,Phenotype tags and legacy perturbation matches are mechanistic screens; they are not biological degeneracy proof without upstream gates.
5,R6,held-out prediction and perturbation robustness,outputs/predictive_validation; outputs/legacy_perturbation,supported,Prediction-limited or fit-only clusters are not biological degeneracy evidence.
6,R7,"clarity, organization, units, and figure traceability",outputs/reviewer_synthesis/manuscript_asset_manifest.csv,supported,Figures/tables must cite source step outputs and conservative claim scope.

## Claim maturity

In [6]:
maturity = result["claim_maturity_table"].drop(columns=["mean_biological_description_score"],errors="ignore")
maturity

,claim,maturity,basis,remaining_requirement
0,accepted cell-specific six-sweep ensembles exist,supported,Step 04 accepted ensemble and held-out-current artifacts,increase accepted/reviewer-facing cell coverage if strata remain sparse
1,candidate mechanism regimes are biologically interpretable,restricted_model_phenotype_support,Step 05 mechanisms plus Step 06 phenotype robustness and Step 09 stratum gates,"biological pathway wording still requires assumption, parameter, and external-validation gates"
2,mechanism or phenotype labels are predictive under perturbation,supported,Step 06 robustness labels and biological_description_score,"broaden support across region, condition, mechanism clusters, and all accepted cells"
3,model assumptions do not drive the conclusion,quantified_model_dependent_or_unresolved,Step 07 sensitivity plus explicit Step 09 assumption gate audit,explicit ECS variant or additional data remains required while the proxy gate fails
4,accepted parameters are physiologically interpretable,semantic_and_identifiability_blocked,Step 08 range/identifiability plus semantic interpretation-class audit,current ranges are guardrails and fitted coordinates are not direct physiological parameters
5,final biological degeneracy wording is allowed,not_allowed_yet,Integrated Step 03-08 synthesis plus restricted all-gate join,"requires mechanism distinction, predictive support, assumption robustness, parameter plausibility, and K_o endpoint support together"

## Manuscript asset manifest

In [7]:
from IPython.display import HTML

manifest = result["manuscript_asset_manifest"].drop(columns=["claim_scope", "exists"], errors="ignore")
manifest_html = manifest.to_html(index=False, escape=True, classes="manifest-table")
display(HTML(
    """
    <style>
    .manifest-table {
        border-collapse: collapse;
        table-layout: fixed;
        width: 100%;
    }
    .manifest-table th,
    .manifest-table td {
        text-align: left;
        vertical-align: top;
        white-space: normal;
        overflow-wrap: anywhere;
        word-break: break-word;
    }
    .manifest-table th:nth-child(1),
    .manifest-table td:nth-child(1) {
        width: 16%;
    }
    .manifest-table th:nth-child(2),
    .manifest-table td:nth-child(2) {
        width: 48%;
        font-family: monospace;
    }
    .manifest-table th:nth-child(3),
    .manifest-table td:nth-child(3) {
        width: 36%;
    }
    </style>
    """
    + manifest_html
))

## Reviewer remark artifact links

For each reviewer remark, these rows list the most useful previous-step artifacts and notebook cells first. The ranking is designed for writing the response letter and manuscript asset manifest.

In [8]:
reviewer_links = result["reviewer_remark_artifact_links"]
reviewer_links

,reviewer_id,impact_rank,usefulness_rationale,source_step,notebook,cell_reference,artifact,artifact_exists
0,R1,1,Separates structural non-identifiability from stronger degeneracy language.,Step 03,analysis/03_combined_identifiability_profiles_fim.ipynb,Effective parameter map / profile summary cells,outputs/identifiability/profile_summary.csv,True
1,R1,2,Shows FV-to-FK mechanistic mapping for top legacy Optuna configurations.,Step 05,analysis/05_mechanistic_decomposition.ipynb,Legacy mechanism/function mapping cells,outputs/legacy_mechanisms/legacy_mechanistic_function_mapping.csv,True
2,R1,3,States what remains before biological degeneracy can be claimed.,Step 09,analysis/09_reviewer_response_synthesis.ipynb,Claim maturity and degeneracy value cells,outputs/reviewer_synthesis/degeneracy_scientific_value_statement.csv,True
3,R2,1,Primary ATF-derived kinetic data and independent cell/sweep accounting.,Step 02,analysis/02_rebuild_atf_thresholds.ipynb,Feature table and region-condition threshold cells,outputs/features/feature_table_by_sweep.csv,True
4,R2,2,Quantifies DH/VH response differences under MFA and MFA+BA.,Step 02,analysis/02_rebuild_atf_thresholds.ipynb,Second-layer regional perturbation cells,outputs/features/experimental_second_layer/matched_sweep_delta_of_delta.csv,True
5,R3,1,Documents model-dependence and assumption-sensitive claims.,Step 07,analysis/07_assumption_sensitivity.ipynb,Assumption gate cells,outputs/assumption_sensitivity/claim_scope_table.csv,True
6,R3,2,Prevents reduced-model proxies from being overinterpreted anatomically.,Step 08,analysis/08_parameter_plausibility_and_constrained_reruns.ipynb,Parameter semantics cells,outputs/parameter_plausibility/parameter_semantics_audit.csv,True
7,R4,1,Audits direct physiology versus effective-coordinate interpretation.,Step 08,analysis/08_parameter_plausibility_and_constrained_reruns.ipynb,Interpretability status cells,outputs/parameter_plausibility/interpretability_status.csv,True
8,R4,2,Provides top legacy Optuna parameter library and source status.,Step 01,analysis/01_postfit_sqlite_pipeline.ipynb,Legacy top-N configuration library cells,outputs/postfit_sqlite/legacy_configuration_library.csv,True
9,R5,1,Defines open/partial/closed and temporal recruitment categories.,Step 05,analysis/05_mechanistic_decomposition.ipynb,Legacy sigmoid/K_o EF category cells,outputs/legacy_mechanisms/legacy_mechanism_categories.csv,True
10,R5,2,Tests how mechanistic classes respond to MFA-like and MFA+BA-like perturbations.,Step 06,analysis/06_predictive_validation_and_perturbation.ipynb,Biological perturbation layer cells,outputs/legacy_perturbation/biological_parameter_direction_summary.csv,True
11,R5,3,Shows whether perturbations change the sigmoid state category.,Step 06,analysis/06_predictive_validation_and_perturbation.ipynb,Sigmoid transition visualization cells,outputs/legacy_perturbation/sigmoid_state_change_summary.csv,True
12,R6,1,Primary conservative prediction/perturbation support table.,Step 06,analysis/06_predictive_validation_and_perturbation.ipynb,Held-out prediction and robustness cells,outputs/predictive_validation/robustness_summary.csv,True
13,R6,2,Compares simulated kinetic directions against ATF perturbation targets.,Step 06,analysis/06_predictive_validation_and_perturbation.ipynb,Experimental direction matching cells,outputs/legacy_perturbation/experimental_direction_match_summary.csv,True
14,R7,1,Lists reviewer-facing artifacts and missing/pending assets.,Step 09,analysis/09_reviewer_response_synthesis.ipynb,Manifest and traceability cells,outputs/reviewer_synthesis/manuscript_asset_manifest.csv,True
15,R7,2,Provides ordered links from each reviewer remark to the most useful generated artifacts.,Step 09,analysis/09_reviewer_response_synthesis.ipynb,Reviewer remark link ledger cells,outputs/reviewer_synthesis/reviewer_remark_artifact_links.csv,True

## Legacy perturbation and mechanistic pathway gates

In [9]:
pathway_gate = result["mechanistic_pathway_perturbation_gate"]
legacy_gate = result["legacy_perturbation_claim_gate"]
degeneracy_value = result["degeneracy_scientific_value_statement"]
display(pathway_gate)
display(legacy_gate)
display(degeneracy_value)

,perturbation_context,feature,n_rows,n_match,n_opposite,n_undefined,match_fraction,sigmoid_transition_rows_available,gate_status,allowed_claim,remaining_requirement
0,MFA_BA_from_MFA_legacy,decay_slope_mV_per_s,162,63,73,0,0.388889,264,screen_not_consistent_or_inconclusive,mechanistic_screen_only_not_biological_proof,"requires broader category coverage, assumption robustness, parameter semantics, and external validation before biological degeneracy wording"
1,MFA_BA_from_MFA_legacy,decay_tau_s,162,0,0,0,0.000000,264,screen_not_consistent_or_inconclusive,mechanistic_screen_only_not_biological_proof,"requires broader category coverage, assumption robustness, parameter semantics, and external validation before biological degeneracy wording"
2,MFA_BA_from_MFA_legacy,peak_depolarization_mV,162,57,78,0,0.351852,264,screen_not_consistent_or_inconclusive,mechanistic_screen_only_not_biological_proof,"requires broader category coverage, assumption robustness, parameter semantics, and external validation before biological degeneracy wording"
3,MFA_BA_from_MFA_legacy,return_slope_mV_per_s,162,0,0,0,0.000000,264,screen_not_consistent_or_inconclusive,mechanistic_screen_only_not_biological_proof,"requires broader category coverage, assumption robustness, parameter semantics, and external validation before biological degeneracy wording"
4,MFA_BA_from_MFA_legacy,rise_slope_mV_per_s,162,68,67,0,0.419753,264,screen_not_consistent_or_inconclusive,mechanistic_screen_only_not_biological_proof,"requires broader category coverage, assumption robustness, parameter semantics, and external validation before biological degeneracy wording"
5,MFA_BA_from_MFA_legacy,rise_tau_s,162,54,76,0,0.333333,264,screen_not_consistent_or_inconclusive,mechanistic_screen_only_not_biological_proof,"requires broader category coverage, assumption robustness, parameter semantics, and external validation before biological degeneracy wording"
6,MFA_BA_from_MFA_legacy,stim_end_depolarization_mV,162,54,81,0,0.333333,264,screen_not_consistent_or_inconclusive,mechanistic_screen_only_not_biological_proof,"requires broader category coverage, assumption robustness, parameter semantics, and external validation before biological degeneracy wording"
7,MFA_BA_from_MFA_legacy,undershoot_magnitude_mV,162,33,34,0,0.203704,264,screen_not_consistent_or_inconclusive,mechanistic_screen_only_not_biological_proof,"requires broader category coverage, assumption robustness, parameter semantics, and external validation before biological degeneracy wording"
8,MFA_BA_stacked_on_control_legacy,decay_slope_mV_per_s,204,91,76,0,0.446078,264,screen_not_consistent_or_inconclusive,mechanistic_screen_only_not_biological_proof,"requires broader category coverage, assumption robustness, parameter semantics, and external validation before biological degeneracy wording"
9,MFA_BA_stacked_on_control_legacy,decay_tau_s,204,17,12,0,0.083333,264,screen_not_consistent_or_inconclusive,mechanistic_screen_only_not_biological_proof,"requires broader category coverage, assumption robustness, parameter semantics, and external validation before biological degeneracy wording"
10,MFA_BA_stacked_on_control_legacy,peak_depolarization_mV,204,72,98,0,0.352941,264,screen_not_consistent_or_inconclusive,mechanistic_screen_only_not_biological_proof,"requires broader category coverage, assumption robustness, parameter semantics, and external validation before biological degeneracy wording"
11,MFA_BA_stacked_on_control_legacy,return_slope_mV_per_s,204,0,0,0,0.000000,264,screen_not_consistent_or_inconclusive,mechanistic_screen_only_not_biological_proof,"requires broader category coverage, assumption robustness, parameter semantics, and external validation before biological degeneracy wording"
12,MFA_BA_stacked_on_control_legacy,rise_slope_mV_per_s,204,75,95,0,0.367647,264,screen_not_consistent_or_inconclusive,mechanistic_screen_only_not_biological_proof,"requires broader category coverage, assumption robustness, parameter semantics, and external validation before biological degeneracy wording"
13,MFA_BA_stacked_on_control_legacy,rise_tau_s,204,91,79,0,0.446078,264,screen_not_consistent_or_inconclusive,mechanistic_screen_only_not_biological_proof,"requires broader category coverage, assumption robustness, parameter semantics, and external validation before biological degeneracy wording"
14,MFA_BA_stacked_on_control_legacy,stim_end_depolarization_mV,204,0,0,0,0.000000,264,screen_not_consistent_or_inconclusive,mechanistic_screen_only_not_biological_proof,"requires broader category coverage, assumption robustness, parameter semantics, and external validation before biological degeneracy wording"
15,MFA_BA_stacked_on_control_legacy,undershoot_magnitude_mV,204,50,43,0,0.245098,264,screen_not_consistent_or_inconclusive,mechanistic_screen_only_not_biological_proof,"requires broader category coverage, assumption robustness, parameter semantics, and external validation before biological degeneracy wording"
16,MFA_like_from_control_legacy,decay_slope_mV_per_s,748,182,283,0,0.243316,264,screen_not_consistent_or_inconclusive,mechanistic_screen_only_not_biological_proof,"requires broader category coverage, assumption robustness, parameter semantics, and external validation before biological degeneracy wording"
17,MFA_like_from_control_legacy,decay_tau_s,748,31,55,0,0.041444,264,screen_not_consistent_or_inconclusive,mechanistic_screen_only_not_biological_proof,"requires broader category coverage, assumption robustness, parameter semantics, and external validation before biological degeneracy wording"
18,MFA_like_from_control_legacy,peak_depolarization_mV,748,0,0,0,0.000000,264,screen_not_consistent_or_inconclusive,mechanistic_screen_only_not_biological_proof,"requires broader category coverage, assumption robustness, parameter semantics, and external validation before biological degeneracy wording"
19,MFA_like_from_control_legacy,return_slope_mV_per_s,748,0,0,0,0.000000,264,screen_not_consistent_or_inconclusive,mechanistic_screen_only_not_biological_proof,"requires broader category coverage, assumption robustness, parameter semantics, and external validation before biological degeneracy wording"
20,MFA_like_from_control_legacy,rise_slope_mV_per_s,748,224,199,0,0.299465,264,screen_not_consistent_or_inconclusive,mechanistic_screen_only_not_biological_proof,"requires broader category coverage, assumption robustness, parameter semantics, and external validation before biological degeneracy wording"
21,MFA_like_from_control_legacy,rise_tau_s,748,214,229,0,0.286096,264,screen_not_consistent_or_inconclusive,mechanistic_screen_only_not_biological_proof,"requires broader category coverage, assumption robustness, parameter semantics, and external validation before biological degeneracy wording"
22,MFA_like_from_control_legacy,stim_end_depolarization_mV,748,0,0,0,0.000000,264,screen_not_consistent_or_inconclusive,mechanistic_screen_only_not_biological_proof,"requires broader category coverage, assumption robustness, parameter semantics, and external validation before biological degeneracy wording"
23,MFA_like_from_control_legacy,undershoot_magnitude_mV,748,0,0,0,0.000000,264,screen_not_consistent_or_inconclusive,mechanistic_screen_only_not_biological_proof,"requires broader category coverage, assumption robustness, parameter semantics, and external validation before biological degeneracy wording"
24,MFA_like_from_mfa_legacy,decay_slope_mV_per_s,594,178,234,0,0.299663,264,screen_not_consistent_or_inconclusive,mechanistic_screen_only_not_biological_proof,"requires broader category coverage, assumption robustness, parameter semantics, and external validation before biological degeneracy wording"
25,MFA_like_from_mfa_legacy,decay_tau_s,594,91,97,0,0.153199,264,screen_not_consistent_or_inconclusive,mechanistic_screen_only_not_biological_proof,"requires broader category coverage, assumption robustness, parameter semantics, and external validation before biological degeneracy wording"
26,MFA_like_from_mfa_legacy,peak_depolarization_mV,594,0,0,0,0.000000,264,screen_not_consistent_or_inconclusive,mechanistic_screen_only_not_biological_proof,"requires broader category coverage, assumption robustness, parameter semantics, and external validation before biological degeneracy wording"
27,MFA_like_from_mfa_legacy,return_slope_mV_per_s,594,0,0,0,0.000000,264,screen_not_consistent_or_inconclusive,mechanistic_screen_only_not_biological_proof,"requires broader category coverage, assumption robustness, parameter semantics, and external validation before biological degeneracy wording"
28,MFA_like_from_mfa_legacy,rise_slope_mV_per_s,594,213,189,0,0.358586,264,screen_not_consistent_or_inconclusive,mechanistic_screen_only_not_biological_proof,"requires broader category coverage, assumption robustness, parameter semantics, and external validation before biological degeneracy wording"
29,MFA_like_from_mfa_legacy,rise_tau_s,594,195,199,0,0.328283,264,screen_not_consistent_or_inconclusive,mechanistic_screen_only_not_biological_proof,"requires broader category coverage, assumption robustness, parameter semantics, and external validation before biological degeneracy wording"
30,MFA_like_from_mfa_legacy,stim_end_depolarization_mV,594,0,0,0,0.000000,264,screen_not_consistent_or_inconclusive,mechanistic_screen_only_not_biological_proof,"requires broader category coverage, assumption robustness, parameter semantics, and external validation before biological degeneracy wording"
31,MFA_like_from_mfa_legacy,undershoot_magnitude_mV,594,0,0,0,0.000000,264,screen_not_consistent_or_inconclusive,mechanistic_screen_only_not_biological_proof,"requires broader category coverage, assumption robustness, parameter semantics, and external validation before biological degeneracy wording"

,gate,gate_status,n_selected_baselines,n_one_dimensional_rows,n_pair_sweep_rows,direction_match_fraction,allowed_claim,forbidden_claim,remaining_requirement
0,legacy_perturbation_claim,first_pass_screen_complete,73,1708,2745,0.150249,legacy_category_perturbation_screen,biologically_proven_degeneracy_or_anatomical_syncytium_count,"full validation requires expanded baselines, external perturbation magnitudes if used, assumption gates, and parameter interpretation gates"

,topic,current_status,objective_scientific_value,remaining_before_stronger_claim,forbidden_overstatement
0,biological_degeneracy_claim,not_biologically_proven,"The current pipeline can still identify constrained model mechanisms, effective-coordinate tradeoffs, K_o functional consequences, and perturbation-response hypotheses. These are valuable as falsifiable mechanistic screens and reviewer-facing guardrails, even when they do not prove biological degeneracy.","Need concurrent support from identifiability, predictive validation, perturbation direction matching, assumption robustness, parameter plausibility, and external biological calibration.","Do not claim anatomical syncytium size from gamma_s_eff * Chi(t), direct physiological parameter truth from fitted effective coordinates, or proven biological degeneracy from model-equivalent fits alone."

## Objective synthesis conclusion

The final row below is generated from the actual upstream outputs. If final biological degeneracy wording is not allowed, the manuscript response should keep the claim at mechanism-screen or prediction-limited maturity and state the unresolved layer explicitly.

In [10]:
final_claim = maturity[maturity["claim"].eq("final biological degeneracy wording is allowed")]
display(final_claim)
assert set(traceability["reviewer_id"]) == {"R1", "R2", "R3", "R4", "R5", "R6", "R7"}
assert set(result["reviewer_remark_artifact_links"]["reviewer_id"]) == {"R1", "R2", "R3", "R4", "R5", "R6", "R7"}
assert "final_biological_degeneracy_claim_allowed" in result["analysis_summary"]
print("Step 09 synthesis outputs written under", PROJECT_ROOT / "outputs" / "reviewer_synthesis")

,claim,maturity,basis,remaining_requirement
5,final biological degeneracy wording is allowed,not_allowed_yet,Integrated Step 03-08 synthesis plus restricted all-gate join,"requires mechanism distinction, predictive support, assumption robustness, parameter plausibility, and K_o endpoint support together"

Step 09 synthesis outputs written under /home/xav/code/astromodel_proving/outputs/reviewer_synthesis

## Restricted claim gates

In [11]:
restricted_join = pd.read_csv(PROJECT_ROOT / "outputs" / "reviewer_synthesis" / "restricted_all_gate_join.csv")
restricted_claims = pd.read_csv(PROJECT_ROOT / "outputs" / "reviewer_synthesis" / "restricted_validation_claims.csv")
assumption_gate = pd.read_csv(PROJECT_ROOT / "outputs" / "reviewer_synthesis" / "assumption_gate_audit.csv")
notebook_screen = pd.read_csv(PROJECT_ROOT / "outputs" / "reviewer_synthesis" / "notebook_update_screen_after_selected_actions.csv")
def _move_after(df: pd.DataFrame, moving: list[str], after: str) -> pd.DataFrame:
    cols = [col for col in df.columns if col not in moving]
    insert_at = cols.index(after) + 1 if after in cols else len(cols)
    for offset, col in enumerate([col for col in moving if col in df.columns]):
        cols.insert(insert_at + offset, col)
    return df[cols]


display(restricted_join.groupby(["validation_label", "restricted_degeneracy_claim_allowed", "blocking_axes"], dropna=False).size().reset_index(name="n_rows"))
display(_move_after(restricted_claims, ["allowed_claim", "forbidden_claim"], "condition"))
display(_move_after(assumption_gate, ["claim_scope"], "assumption_axis"))
display(notebook_screen)

       validation_label  restricted_degeneracy_claim_allowed                                     blocking_axes  n_rows
0  predictive_supported                                False  assumptions;parameter_step08;parameter_semantics      29

  mechanism_cluster region condition                                allowed_claim                                         forbidden_claim      validation_label  restricted_all_gate_pass                                     blocking_axes
0                M2     DH   CONTROL  predictive model-derived mechanism scenario  broad biological degeneracy or pathway-level phenotype  predictive_supported                     False  assumptions;parameter_step08;parameter_semantics
1                M2     DH       MFA  predictive model-derived mechanism scenario  broad biological degeneracy or pathway-level phenotype  predictive_supported                     False  assumptions;parameter_step08;parameter_semantics
2                M2     DH    MFA_BA  predictive model-derived mechanism scenario  broad biological degeneracy or pathway-level phenotype  predictive_supported                     False  assumptions;parameter_step08;parameter_semantics
3                M2     VH       MFA  predictive model-derived mechanism scenario  broad biological degeneracy or pathway-level phenotype  predictive_supported                     False  assumptions;parameter_step08;parameter_semantics
4                M2     VH    MFA_BA  predictive model-derived mechanism scenario  broad biological degeneracy or pathway-level phenotype  predictive_supported                     False  assumptions;parameter_step08;parameter_semantics
5                M3     DH   CONTROL  predictive model-derived mechanism scenario  broad biological degeneracy or pathway-level phenotype  predictive_supported                     False  assumptions;parameter_step08;parameter_semantics
6                M3     DH       MFA  predictive model-derived mechanism scenario  broad biological degeneracy or pathway-level phenotype  predictive_supported                     False  assumptions;parameter_step08;parameter_semantics
7                M3     DH    MFA_BA  predictive model-derived mechanism scenario  broad biological degeneracy or pathway-level phenotype  predictive_supported                     False  assumptions;parameter_step08;parameter_semantics
8                M3     VH       MFA  predictive model-derived mechanism scenario  broad biological degeneracy or pathway-level phenotype  predictive_supported                     False  assumptions;parameter_step08;parameter_semantics
9                M3     VH    MFA_BA  predictive model-derived mechanism scenario  broad biological degeneracy or pathway-level phenotype  predictive_supported                     False  assumptions;parameter_step08;parameter_semantics

                     assumption_axis                                                                                              claim_scope  n_rows                    metric  metric_value  threshold  gate_pass gate_status
0                        gating_form                                      same-parameter gating-family screen; refit-level test still pending     174         unstable_fraction      0.000000       0.25       True        pass
1       intracellular_K_as_ECS_proxy  proxy exclusion can restrict claims; explicit ECS variant still needed for broad ECS-homeostasis claims      29    proxy_limited_fraction      0.862069       0.25      False        fail
2  local_syncytial_compartment_split  lumped split appears stable in current screen if gate passes; spatial-scale validation remains separate      29  split_sensitive_fraction      0.103448       0.25       True        pass

,notebook,rerun_required,comment_update_recommended,action_taken,remaining_action,reason
0,outputs/executed_notebooks/00_data_provenance_and_trace_audit.ipynb,False,False,none_required,none,Selected actions reuse downstream Step 04-08 outputs and do not change data provenance.
1,outputs/executed_notebooks/01_feature_extraction_and_qc.ipynb,False,False,none_required,none,Feature thresholds are consumed by the interpolation screen but were not modified.
2,outputs/executed_notebooks/02_feature_contracts_and_region_aware_thresholds.ipynb,False,False,none_required,none,Region-aware feature bands are reused unchanged by the new gate audits.
3,outputs/executed_notebooks/03_combined_identifiability_profiles_fim.ipynb,False,False,none_required,none,Step 03 identifiability evidence is reused unchanged in cell-specific and semantic parameter audits.
4,outputs/executed_notebooks/04_cell_specific_six_sweep_fitting.ipynb,False,False,none_required,none,No Step 04 refit is performed; full accepted ensemble and candidate history are reused.
5,outputs/executed_notebooks/05_mechanistic_decomposition.ipynb,False,False,interpretation_centralized_in_step09,optional_future_cross_reference_only,"New interpolation and phenotype-threshold audits qualify Step 05 mechanism labels, but core Step 05 outputs are unchanged and Step 09 now reports the derived interpretation."
6,outputs/executed_notebooks/06_predictive_validation_and_perturbation.ipynb,False,False,interpretation_centralized_in_step09,optional_future_cross_reference_only,"New phenotype robustness, prediction-limited failure, and K_o endpoint summaries refine interpretation of existing Step 06 outputs and are reported by Step 09."
7,outputs/executed_notebooks/07_assumption_sensitivity.ipynb,False,False,interpretation_centralized_in_step09,optional_future_cross_reference_only,All-current and proxy-exclusion audits refine Step 07 interpretation and are reported by Step 09; no optimizer rerun is required.
8,outputs/executed_notebooks/08_parameter_plausibility_and_constrained_reruns.ipynb,False,False,interpretation_centralized_in_step09,optional_future_cross_reference_only,"Full-ensemble, semantic-class, citation, and cell-specific spread audits strengthen Step 08 guardrails and are reported by Step 09 without changing Step 08 core calculations."
9,outputs/executed_notebooks/09_reviewer_response_synthesis.ipynb,False,False,updated_and_rerun,none_unless_selected_action_gates_change,"Step 09 was updated to incorporate selected-action gates in claim maturity, manifest outputs, and post-execution interpretation."

## Post-execution scientific status

Executed status for reviewer response after selected actions: Step 09 integrates R1-R7 into 7 traceability rows, 6 claim-maturity rows, and a complete expanded manuscript manifest. The selected gate audits produce no-refit/current-output evidence plus modest sensitivity screens. They raise the mechanism-regime claim only to `restricted_model_phenotype_support`, because some model-derived phenotype/stratum gates pass. They do **not** support global biological degeneracy: the restricted all-gate join has no passing row, the intracellular-K proxy assumption gate fails, and parameter semantics/identifiability block direct physiological parameter wording. Final biological degeneracy wording therefore remains `not_allowed_yet`.

Notebook-screen result: core Steps 05-08 do not require computational reruns because their source outputs were reused unchanged, but their interpretation comments can optionally point to the new derivative audits. Step 09 must be rerun whenever these selected-action gates change.